export default {
    BackgroundSourceTypes: {
        GRAIN: 'GRAIN',
        PARSLEY: 'PARSLEY',
        BEANS: 'BEANS',
    },
    APP_WELCOME_TEXT: 'WELCOME TO 8FIT',
    QUESTION_GOAL: "What's your goal?",
    QUESTION_AGE: 'How old are you?',
    QUESTION_HEIGHT: 'How tall are you?',
    QUESTION_CONFIRM: 'Confirm your details:',
    CONTINUE: 'Continue',
    SAVE: 'Save',
    CM: 'Cm',
    FT: 'Ft',
    IN: 'In',
    CM_TOGGLE_TITLE: 'CM',
    FT_TOGGLE_TITLE: 'FT',
    GOAL: 'Goal',
    AGE: 'Age',
    HEIGHT: 'Height',
}